### PR TITLE
Add `log_level` option

### PR DESCRIPTION
**Pull request by vorce**

### CODE REVIEW

**Comment by vorce** [comment]
hey @aserafin what do you think about this addition?

**Comment by aserafin** [comment]
Looks good :) I will merge and release during the weekend - thank you very much 👍

**Comment by aserafin** [comment]
Thanks for your wrk @vorce - new version is out there https://rubygems.org/gems/grape_logging/versions/1.5.0 🎉

**Comment by vorce** [comment]
Cheers!

**Pull request merged**
